Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -188,6 +188,9 @@ jobs:
             echo "docker user created"
             
             echo "docker compose stage start"
+            if ! command -v docker-compose &> /dev/null; then
+            echo "❌ Docker Compose not found. Installing..."
+
             if ! docker-compose version &> /dev/null && ! docker-compose version &> /dev/null; then
               echo "Docker Compose not found. Installing..."
               sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose || { echo "::error:: Failed to download Docker Compose."; exit 1; }
@@ -211,7 +214,7 @@ jobs:
 
             # Set AWS Region
             AWS_REGION="us-east-1"
-            
+
             BACKEND_SECRET=$(aws secretsmanager get-secret-value --secret-id BackendSecrets --query SecretString --output text || echo "")
             FRONTEND_SECRET=$(aws secretsmanager get-secret-value --secret-id FrontendSecrets --query SecretString --output text || echo "")
            
