Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -195,7 +195,7 @@ jobs:
               echo "Docker Compose not found. Installing..."
               sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose || { echo "::error:: Failed to download Docker Compose."; exit 1; }
               sudo chmod +x /usr/local/bin/docker-compose || { echo "::error:: Failed to set permissions for Docker Compose."; exit 1; }
-              sudo chown ec2-user:ec2-user /usr/local/bin/docker compose || { echo "::error:: Failed to change ownership for Docker Compose."; exit 1; }
+              sudo chown ec2-user:ec2-user /usr/local/bin/docker-compose || { echo "::error:: Failed to change ownership for Docker Compose."; exit 1; }
               echo " Docker Compose installation completed."
             else
               echo " Docker Compose is already installed $(docker-compose version)"
@@ -213,7 +213,7 @@ jobs:
             fi
 
             # Set AWS Region
-            AWS_REGION="us-east-1"
+            export AWS_REGION="us-east-1"
 
             BACKEND_SECRET=$(aws secretsmanager get-secret-value --secret-id BackendSecrets --query SecretString --output text || echo "")
             FRONTEND_SECRET=$(aws secretsmanager get-secret-value --secret-id FrontendSecrets --query SecretString --output text || echo "")
