Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -18,7 +18,7 @@ jobs:
         uses: hashicorp/setup-terraform@v2
         with:
           terraform_version: latest
-
+      
       - name: Test AWS CLI Access
         run: |
           aws sts get-caller-identity
@@ -30,6 +30,14 @@ jobs:
 
       - name: Initialize Terraform
         run: terraform init
+        working-directory: infrastructure
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_REGION: us-east-1
+
+      - name: Refresh Terraform State
+        run: terraform apply -refresh-only -auto-approve
         working-directory: infrastructure
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -106,6 +114,15 @@ jobs:
         with:
           secrets: FrontendSecrets
           parse-json: true
+
+      - name: Print EC@ Public IP
+        run: |
+          echo "Received EC2 Public IP - '${{ needs.terraform.outputs.ec2_public_ip }}'"
+          if [[ -z "${{ needs.terraform.outputs.ec2_public_ip }}" ]]; then
+            echo "::error:: No Public IP retrieved from Terraform!"
+            exit 1
+          fi
+
 
       - name: Print EC2 Public IP
         run: echo "Received EC2 Public IP - '${{ needs.terraform.outputs.ec2_public_ip }}'"
