Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -190,11 +190,11 @@ jobs:
             echo "docker compose stage start"
 
 
-            if ! docker-compose version &> /dev/null && ! docker-compose version &> /dev/null; then
+            if ! docker compose version &> /dev/null && ! docker-compose version &> /dev/null; then
               echo "Docker Compose not found. Installing..."
               sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose || { echo "::error:: Failed to download Docker Compose."; exit 1; }
               sudo chmod +x /usr/local/bin/docker-compose || { echo "::error:: Failed to set permissions for Docker Compose."; exit 1; }
-              sudo chown ec2-user:ec2-user /usr/local/bin/docker-compose || { echo "::error:: Failed to change ownership for Docker Compose."; exit 1; }
+              sudo chown ec2-user:ec2-user /usr/local/bin/docker compose || { echo "::error:: Failed to change ownership for Docker Compose."; exit 1; }
               echo " Docker Compose installation completed."
             else
               echo " Docker Compose is already installed $(docker-compose version)"
@@ -220,8 +220,8 @@ jobs:
            
             # Save secrets to text files
             echo "creating test files now"
-            echo "$BACKEND_SECRET" > ~/backend_env.txt
-            echo "$FRONTEND_SECRET" > ~/frontend_env.txt
+            echo "${{BACKEND_SECRET}}" > ~/backend_env.txt
+            echo "${FRONTEND_SECRET}" > ~/frontend_env.txt
 
            
             if [[ -z "$BACKEND_SECRET" ]]; then
@@ -264,13 +264,13 @@ jobs:
 
             # Deploy with Docker Compose
             echo "⬇️ Pulling latest Docker images..."
-            docker-compose pull
+            docker compose pull
 
             echo "🛑 Stopping existing containers (if any)..."
-            docker-compose down || true
+            docker compose down || true
 
             echo "🚀 Starting database container..."
-            docker-compose up -d db && sleep 20
+            docker compose up -d db && sleep 20
 
             DB_HEALTH=$(docker inspect mysql_db --format='{{.State.Health.Status}}' || echo "")
 
