Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -171,9 +171,13 @@ jobs:
             sudo systemctl start docker && sudo systemctl enable docker
             sudo usermod -aG docker ec2-user
 
-            # install docker compose
-            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-            sudo chmod +x /usr/local/bin/docker-compose
+            if ! command -v docker-compose &> /dev/null; then
+              echo "⚡ Docker Compose not found. Installing..."
+              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+              sudo chmod +x /usr/local/bin/docker-compose
+            else
+              echo "✅ Docker Compose is already installed."
+            fi
 
             # Set up application directories
             mkdir -p ~/app && cd ~/app
